// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleFooter: typeof import('./src/components/article/ArticleFooter.vue')['default']
    ArticleHeader: typeof import('./src/components/article/ArticleHeader.vue')['default']
    ArticleList: typeof import('./src/views/article/ArticleList.vue')['default']
    Backtop: typeof import('./src/components/Backtop.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HeaderBar: typeof import('./src/components/layout/HeaderBar.vue')['default']
    HotKey: typeof import('./src/components/markdown/HotKey.vue')['default']
    LeftBar: typeof import('./src/components/layout/LeftBar.vue')['default']
    RightBar: typeof import('./src/components/layout/RightBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleArticle: typeof import('./src/components/article/SimpleArticle.vue')['default']
    SingleArticle: typeof import('./src/components/article/SingleArticle.vue')['default']
    TagsSelect: typeof import('./src/components/TagsSelect.vue')['default']
  }

}
